### PR TITLE
[252] [Logo] Consolidate and update favicons app images with white background

### PR DESCRIPTION
**Pull request by markcipolla**
REFS https://trello.com/c/LfVxhHMc/252-logo-consolidate-and-update-favicons-app-images-with-white-background#

This PR updates the 114x114 and 192x192 logo PNGs to have white backgrounds, so they'll look 😗👌 when used as 'app' images for Android and Apple.

I've also generated a new `favicon.ico` (the good 'ol 16x16px fuzzy one), with the new logo. We can use this across our apps, instead of one per app!

Screen Shot 2019-05-31 at 3 35 46 pm

### CODE REVIEW

**Comment by nickbrowne** [comment]
It makes sense for the app icons but are we sure we want a white background for the favicon? 

A survey of the icons in my browser shows this is uncommon and I'm not sure it will look as neat.
Screenshot at 2019-05-31 15-42-02

Also the existing favicon was high-dpi friendly, this one is definitely not.

**Comment by jameshill** [comment]
Should we make an icon for the apple-touch ref

```
<link rel="apple-touch-icon" href="apple-touch-icon.png">
```

**Comment by markcipolla** [comment]
> Also the existing favicon was high-dpi friendly (with variants for regular dpi and high dpi), this one is definitely not.

The existing one is not high DPI. it was 32x32.


> It makes sense for the app icons but are we sure we want a white background for the favicon?

Good point, I'll remove the white bkg.

**Comment by markcipolla** [comment]
> Should we make an icon for the apple-touch ref

We already do; we use the 114x114.

`<link rel="apple-touch-icon-precomposed" href="<%= webpack_asset_path('logo-114x114.png') %>">`

**Comment by nickbrowne** [comment]
That is high DPI when it comes to favicons, the current one is packed with a 16px (regular) and a 32px (high) version:

Screenshot at 2019-05-31 15-52-06

**Comment by jameshill** [comment]
> We already do; we use the 114x114.
> 
> `<link rel="apple-touch-icon-precomposed" href="<%= webpack_asset_path('logo-114x114.png') %>">`

I mean, should we split them so they're not both on the logo-114x114.png

i.e. 

- keep `logo-114x114.png` with the transparency
- create a new long without the transparency for apple-touch-icon something like `apple-touch-icon-114x114.png`

**Comment by markcipolla** [comment]
I've updated all logos with the right colours, and @nickbrowne helped me craft a brand spanking new favicon!

**Comment by markcipolla** [comment]
> * keep `logo-114x114.png` with the transparency
> 
> * create a new long without the transparency for apple-touch-icon something like `apple-touch-icon-114x114.png`

Done.

**Pull request merged**
