### PR TITLE
[526] Update @material-ui to 4.2.0

### PR DESCRIPTION
**Pull request by markcipolla**
https://trello.com/c/OCkepBuq/526-update-materialui-to-420

To unblock https://github.com/conversation/ui/pull/78, @nickbrowne and I went about upgrading TCUI to use `@material-ui/core` to 4.2.0.

We also found that we had to upgrade `@material-ui/icons` and `@material-ui/lab` (due to peer dependencies), and `material-ui-pickers` was merged into MterialUI to become`@material-ui/pickers`.

### CODE REVIEW

**Comment by tiagoamaro** [comment]
Besides the `package-lock.json` file, diff is quite small!

Noticed a few differences after the update: input labels font seems different and stories spacing (`GridLayout`) has no gap:

- Before

Screenshot from 2019-07-08 09-55-31

image

- After

Screenshot from 2019-07-08 09-55-02

image

**Comment by nullobject** [comment]
You legends 😻

**Comment by markcipolla** [comment]
>     * Before
> 
> 
> Screenshot from 2019-07-08 09-55-31
> 
> image
> 
>     * After
> 
> 
> Screenshot from 2019-07-08 09-55-02
> 
> image



> Noticed a few differences after the update: input labels font seems different and stories spacing (`GridLayout`) has no gap:

Looking into this.

**Comment by markcipolla** [comment]
> Noticed a few differences after the update: input labels font seems different and stories spacing (`GridLayout`) has no gap:

Thankfully, it was pretty straightforward. We had spacing of `16` units (?) for the `Grid`. It's API has changed, it now expects an enum between 0 and 10 (for some reason)...

Screen Shot 2019-07-09 at 10 07 11 am
https://material-ui.com/api/grid/

**Comment by nullobject** [comment]
I'm just having a look through the new Storybook, I noticed an issue with some of the fonts.

before:

Screen Shot 2019-07-09 at 3 34 29 pm

after:

Screen Shot 2019-07-09 at 3 34 13 pm

**Comment by markcipolla** [comment]
> I noticed an issue with some of the fonts.

Hmmm 🤔 . It's using Libre Baskerville, so at least it's picking a font we've selected. I'll investigate.

**Comment by nickbrowne** [comment]
Possibly some of the typography variants have been renamed or something.

**Comment by markcipolla** [comment]
>  noticed an issue with some of the fonts.

Also, laser eyes mate! 👏 

giphy

**Comment by tiagoamaro** [comment]
Just tested this PR's latest commit against analytics, and the web console is reporting the following:

```
Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.

You can use the `https://github.com/mui-org/material-ui/tree/master/packages/material-ui-codemod/README.md#theme-spacing-api` migration helper to make the process smoother.
```

Just saw that a couple of `theme.spacing.unit` were hanging around. Going to fixup a commit and rebase it.

**Comment by nullobject** [comment]
Nice work, thanks for this 👏

**Pull request merged**
