### PR TITLE
[67] Update logos

### PR DESCRIPTION
**Pull request by markcipolla**
REFS https://trello.com/c/1JwyZTFE/67-logo-update-logo-in-masthead-of-website

With our new brandmark from @ZoeJazz, we have to update assets across the apps. 

Previously, we used a (now defunkt) lib, https://github.com/conversation/tc-assets, which I created to hold the assets for this very reason; update it in one place, and all apps would get the updated logos.

However, I also added to the TC-Assets lib the first parts a component library, with storybook; it's up at  https://design.theconversation.com/

Since we've gone in a very different direction, I'm suggesting:

- [x] we put the new logos in TC-UI
- [ ] bump the TCUI version, and pull it into TC
- [ ] TC will have small changes, as I've consolidated a few files so we have a reduced list of logos.

### CODE REVIEW

**Comment by markcipolla** [comment]
@nullobject an interesting addition to tcui. If you have some clever thoughts on how we could bundle assets, 👂

**Comment by ZoeJazz** [comment]
Hey @markcipolla - I don't appear to have the updated logo in https://design.theconversation.com/

Actually, I might not be checking this correctly. Let me know best steps for review.

Cheers,
z

**Comment by markcipolla** [comment]
> Hey @markcipolla - I don't appear to have the updated logo in https://design.theconversation.com/
> 
> Actually, I might not be checking this correctly. Let me know best steps for review.
> 

> Cheers,
> z

design.theconversation.com is the old, now defunkt. It shows old and out of date assets. That one you can ignore, as it'll get removed. 
How to view the logos? Let's use Github:

Kapture 2019-05-28 at 10 00 59

**Comment by nullobject** [comment]
@markcipolla Hmm 🤔

How were we actually using the assets out of the old library?

**Comment by markcipolla** [comment]
> How were we actually using the assets out of the old library?

In TC, we were pulling in the whole directory: 

`app/assets/javascripts/images:js`

```
require.context("tc-assets/logos", true);
```

**Comment by markcipolla** [comment]
[[67] Update logos](https://trello.com/c/2Auu8W2K/246-67-update-logos)

**Comment by markcipolla** [comment]
[Add Logos to TCUI](https://trello.com/c/dwln2V9y/247-add-logos-to-tcui)

**Comment by markcipolla** [comment]
> require.context("tc-assets/logos", true);

Further clarification: This is so webpack knows there are files in that folder, and auto-adds them to the `manifest.json` (without explicitly being `import`'d); that way, they're available to call outside of client-side JS and in the erb views using `webpack_asset_path`.

**Comment by ZoeJazz** [comment]
Heya - Heads up that the favicon might need to have a white background in order to support app tile view. 
IMG_7726

**Comment by markcipolla** [comment]
> Heads up that the favicon might need to have a white background in order to support app tile view.

HMMMM 🤔 I'm 99% sure (will double check) that Apple uses the `src/logos/logo-192x192.png` file; that has a transparent background, so yeah, will need a white one... 
I'd do both.

Also, as the real head turner, this lib doesn't yet have the actual favicon file. Each app has their own. We should add it (along with the white-backgrounded images) in another PR and consolidate it across the apps!

**Comment by ZoeJazz** [comment]
Hey @markcipolla - Just checking if we applied a white background to our app icon? If not, let me know how I can help.

CC @jameshill 
IMG_477D881AF137-1

**Comment by markcipolla** [comment]
> Hey @markcipolla - Just checking if we applied a white background to our app icon? If not, let me know how I can help.

Yep

https://cdn.theconversation.com/static/tc/@theconversation/ui/dist/logos/web-app-logo-114x114-827839977dc24988cadfa3bd6c814600.png
https://cdn.theconversation.com/static/tc/@theconversation/ui/dist/logos/web-app-logo-192x192-e99834e3a7a551050e9debe6cc925617.png
https://cdn.theconversation.com/static/tc/@theconversation/ui/dist/logos/favicon-ae7bd7a3096e6cda828b4576fa9b32c6.ico

If you delete that icon shortcut, log in as a platform team member on your mobile, and resave it as "an app", and it should be on a white background.

**Comment by ZoeJazz** [comment]
Ok great :) All those examples appear to be transparent. If this is a caching issue for non-platform team members then I'll check back later. Thanks so much @markcipolla

**Pull request merged**
